version: '3'
services:

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - TO_EXPOSE_PORT=3000
    ports:
      - '3000:3000'
    networks:
      - network_all

  backend:
    build:
        context: ./backend
        dockerfile: Dockerfile
    environment:
      - TO_EXPOSE_PORT=8080
    ports:
      - '8080:8080'
    networks:
      - network_all

networks:
  network_all: